- app/views/components/_navbar.html.erb
> Fixed links for the navbar

- app/controllers/pages_controller.rb
- app/views/components/_banner.html.erb
- app/views/pages/kitchen_sink.html.erb
- config/routes.rb
> created the kitchen sink file

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_room-card.scss
- app/views/components/_banner.html.erb
- app/views/components/_room-card.html.erb
- app/views/pages/kitchen_sink.html.erb
> Finished card

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/footer.scss
- app/views/components/_footer.html.erb
- app/views/pages/kitchen_sink.html.erb
> created le footer

- Gemfile
- Gemfile.lock
- app/policies/application_policy.rb
added pundit gem. no policies added yet.
> pundit installed - no pundit policies yet

- app/controllers/application_controller.rb
2nd try - apologies if this pops up a few times - included before_action and private method in the application controller.
> pundit install 2 before action on application controller

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
> Added the devise views

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/rooms_controller.rb
- app/views/pages/home.html.erb
- app/views/rooms/index.html.erb
- config/routes.rb
- test/controllers/rooms_controller_test.rb
add rooms controller and index view
> add rooms controller and index view

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/components/_navbar.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20200225175925_add_owner_to_user.rb
- db/schema.rb
Finished the sign up form with the new owner field.
> Finished the sign_up registration

- app/controllers/rooms_controller.rb
> Fixed typo on create for rooms

- app/views/components/_banner.html.erb
Fixed the link for sign up button
> Fixed the call to action link

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/seeds.rb
> Finished the seed file

- app/views/components/_banner.html.erb
> Finished the logic of call to action

- app/assets/stylesheets/components/_room-card.scss
- app/controllers/pages_controller.rb
- app/views/components/_featured-rooms.html.erb
- app/views/components/_room-card.html.erb
- app/views/rooms/index.html.erb
Added card functionality and decorations
> added card decoration and functionality

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_room-card.scss
- app/views/rooms/index.html.erb
Added the links to the index page
> Finished the links in the index page

- app/views/rooms/show.html.erb
Added the prices to the show table
> Added the prices to the show table

- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/views/bookings/new.html.erb
- app/views/components/_flashes.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
Please review these changes. Booking Alert created as a flash under components. Also added a "notice" capability. Deleted the booking/new route and controller.
> created booking confirmation notice and alert option in components

- app/controllers/rooms_controller.rb
- app/views/devise/registrations/new.html.erb
> fixed the owners bug and the picture new room bug

- app/views/rooms/show.html.erb
that bih was lookin skinny af i so i fattened it up
> tweaked form responsive display

- app/javascript/packs/application.js
- app/javascript/plugins/init_flatpickr.js
- app/models/booking.rb
- app/models/room.rb
- app/views/rooms/show.html.erb
- db/seeds.rb
- package.json
- yarn.lock
Added the logic for the calendar
> Finished the calendar

- app/views/devise/registrations/new.html.erb
- app/views/rooms/show.html.erb
> Sign up style

- app/assets/stylesheets/components/_navbar.scss
> make navbar sticky

- app/views/components/_footer.html.erb
> fix sidescroll caused by footer

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/mailer.html.erb
- app/views/rooms/new.html.erb
> create consistency across forms for real this time pt 1

- app/views/components/_navbar.html.erb
Added my bookings button to navbar
> added a button to the navbar for my bookings

- app/controllers/rooms_controller.rb
- app/javascript/plugins/init_mapbox.js
- db/seeds.rb
> Finished the final seed file

- app/assets/stylesheets/components/_booking.scss
- app/assets/stylesheets/components/_index.scss
- app/views/rooms/show.html.erb
> Finished fixing
